In [2]:
import numpy as np

In [3]:
np.__version__


'2.4.1'

## Create and read Numpy array

#### 1D Array

#### 1D array is just a simple array without any rows and columns

In [4]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(5,)

In [7]:
# for Datatype of array
arr1.dtype

dtype('int64')

In [8]:
#to check the dimention of the array
arr1.ndim

1

In [9]:
#check size of the array
arr1.size

5

### 2D Array 

In [10]:
# array inside array

arr2 = np.array([[1,2,3],
                [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr2.ndim

2

In [12]:
arr2.shape


(2, 3)

### 3D ARRAY

#### It is like array inside of array inside of array

In [13]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[3,2,1],[6,2,3]],[[1,1,1],[0,0,0]]])

In [14]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [6, 2, 3]],

       [[1, 1, 1],
        [0, 0, 0]]])

In [15]:
arr3.ndim

3

In [16]:
arr3.shape

(3, 2, 3)

### Create Random arrays

In [17]:
randomArr = np.random.rand(3,2,3)

In [18]:
randomArr

array([[[0.56497072, 0.57505328, 0.47079147],
        [0.25324854, 0.89307307, 0.57723493]],

       [[0.81435071, 0.3173341 , 0.9315153 ],
        [0.20582171, 0.01612684, 0.13532229]],

       [[0.05431446, 0.88243545, 0.68310432],
        [0.20922197, 0.78104267, 0.43013184]]])

In [19]:
randomArr.dtype

dtype('float64')

In [20]:
#creating array of zeros
zeroArr = np.zeros((2,2,3))
zeroArr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
# replacing array with other number using full function
full = np.full((2,2,3),7)

In [22]:
full

array([[[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]]])

In [23]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [6, 2, 3]],

       [[1, 1, 1],
        [0, 0, 0]]])

In [24]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr3[0][1][2]

np.int64(6)

In [26]:
# can use slicing
arr3[0:2]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [6, 2, 3]]])

In [27]:
  arr3[1,0,2]

np.int64(1)

## Update and Delete

In [28]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)

In [29]:
a1

array([[[0.59054806, 0.51513472],
        [0.99993744, 0.90986708],
        [0.08919151, 0.89412879]],

       [[0.04155092, 0.08447843],
        [0.02821478, 0.45988627],
        [0.40451407, 0.14982857]]])

In [30]:
a2

array([[[0.75101043, 0.24888826],
        [0.34255588, 0.94454592],
        [0.10404884, 0.26833206]],

       [[0.7108277 , 0.58825128],
        [0.53177766, 0.47085385],
        [0.02935694, 0.38565168]]])

### Basic Math Operations

In [31]:
np.add(a1,a2)

array([[[1.3415585 , 0.76402298],
        [1.34249332, 1.854413  ],
        [0.19324036, 1.16246085]],

       [[0.75237863, 0.67272971],
        [0.55999244, 0.93074012],
        [0.43387101, 0.53548025]]])

In [32]:
np.subtract(a1,a2)

array([[[-0.16046237,  0.26624645],
        [ 0.65738157, -0.03467884],
        [-0.01485733,  0.62579672]],

       [[-0.66927678, -0.50377285],
        [-0.50356288, -0.01096758],
        [ 0.37515712, -0.23582311]]])

In [33]:
np.divide(a1,a2)

array([[[ 0.78633803,  2.0697429 ],
        [ 2.91904915,  0.96328518],
        [ 0.85720812,  3.33217274]],

       [[ 0.05845428,  0.14360943],
        [ 0.05305748,  0.97670703],
        [13.77916132,  0.3885075 ]]])

In [34]:
np.multiply(a1,a2)

array([[[0.44350776, 0.12821098],
        [0.34253445, 0.85941124],
        [0.00928027, 0.23992342]],

       [[0.02953555, 0.04969455],
        [0.01500399, 0.21653922],
        [0.0118753 , 0.05778164]]])

### Statistical functions

In [35]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
logs = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [36]:
sqrt

np.float64(5.0)

In [37]:
abs

np.int64(2)

In [38]:
power

np.int64(256)

In [39]:
logs

np.float64(3.2188758248682006)

In [40]:
mins

np.float64(0.02821478032727165)

In [41]:
maxs

np.float64(0.9445459187211495)

### Update

In [42]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [6, 2, 3]],

       [[1, 1, 1],
        [0, 0, 0]]])

In [43]:
arr3[0,0,2] = 50

In [44]:
arr3

array([[[ 1,  2, 50],
        [ 4,  5,  6]],

       [[ 3,  2,  1],
        [ 6,  2,  3]],

       [[ 1,  1,  1],
        [ 0,  0,  0]]])

In [45]:
arr3.sort()
arr3

array([[[ 1,  2, 50],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 2,  3,  6]],

       [[ 1,  1,  1],
        [ 0,  0,  0]]])

In [46]:
# REshaping
arr3.shape

(3, 2, 3)

In [47]:
reshapeArray = arr3.reshape(2,3,-1)

In [48]:
reshapeArray

array([[[ 1,  2, 50],
        [ 4,  5,  6],
        [ 1,  2,  3]],

       [[ 2,  3,  6],
        [ 1,  1,  1],
        [ 0,  0,  0]]])

## Appending and Inserting

In [51]:
zeroArr


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [54]:
zeros = np.zeros((3,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [55]:
ones = np.ones((3,2,3))

In [56]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [63]:
# appending
new_arr = np.append(zeros,ones, axis = 0)

In [64]:
new_arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [66]:
#insert array
insert_array = np.insert(zeros, 2, ones, axis = 0)
insert_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [69]:
#DELETE
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.55473009, 0.46187865, 0.83191377],
        [0.03871906, 0.03283478, 0.8807272 ]],

       [[0.11154729, 0.68780221, 0.53739252],
        [0.6436052 , 0.27342936, 0.40296672]],

       [[0.43986534, 0.9990053 , 0.40463711],
        [0.41548702, 0.04589098, 0.79875301]]])

In [73]:
arr5 = np.delete(arr4, 1, axis=1) #(arry, index, axis)
arr5

array([[[0.55473009, 0.46187865, 0.83191377]],

       [[0.11154729, 0.68780221, 0.53739252]],

       [[0.43986534, 0.9990053 , 0.40463711]]])

In [74]:
# saving the array
np.save("save_array",arr5)

In [75]:
# to load the file or array
np.load("save_array.npy")

array([[[0.55473009, 0.46187865, 0.83191377]],

       [[0.11154729, 0.68780221, 0.53739252]],

       [[0.43986534, 0.9990053 , 0.40463711]]])